### ISSUE TITLE
Instructions on wiki result in an error

### ISSUE THREAD

**Issue by timcowlishaw** [nationalarchives/tna-frontend#96]
Hey folks!

One quick issue i identified when trying to integrate the tna-frontend in nationalarchives/ds-caselaw-public - the instructions [on the wiki](https://github.com/nationalarchives/tna-frontend/wiki/Using-TNA-Frontend) result in an error because `$largest-container-width` is defined in px, then used in a `calc` statement with a variable defined in `rem`. I can't work out how to send a PR against a wiki page, but suggest the example here is changed to give a width in `rem`?

thanks!

Tim

**Comment by ahosgood** [comment]
Very good spot! Thank you, I have updated the wiki. 👍🏼
